In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("House-Prices.csv")
df.head()

Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790       2.0          2       2    No         East
1     2  114200  2030       4.0          2       3    No         East
2     3  114800  1740       3.0          2       1    No         East
3     4   94700  1980       NaN          2       3    No         East
4     5  119800  2130       3.0          3       3    No         East

In [3]:
model = linear_model.LinearRegression().fit(df[['SqFt']], df.Price)

In [4]:
model.coef_

array([70.22631824])

In [5]:
model.intercept_

-10091.129909123061

In [7]:
model.predict([[5000]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([341040.4613053])

In [8]:
import pickle

In [9]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [10]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [12]:
mp.predict([[5000]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([341040.4613053])

In [14]:
%pip install joblib

Note: you may need to restart the kernel to use updated packages.


In [15]:
import joblib

In [16]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [17]:
mj = joblib.load('model_joblib')

In [18]:
mj.predict([[5000]])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([341040.4613053])